include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    avoid_print: warning

  exclude:
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
    - lib/l10n/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/**/*.g.dart

linter:
  rules:
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    cascade_invocations: false

    public_member_api_docs: true
    flutter_style_todos: true
    always_use_package_imports: true
    avoid_relative_lib_imports: true


formatter:
  page_width: 100
  trailing_commas: preserve 
